---
title: "Drake Pipeline"
author: Phil Chapman
date: 2019-01-29
output: 
    html_document:
        number_sections: yes
        theme: cosmo
        highlight: tango
        toc: yes
        toc_depth: 3
        code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Introduction



# Set up

## Load R libraries

```{r, message=FALSE}
library(dplyr)
library(ggplot2)
library(gapminder)
library(future)
library(drake)
```


# Drake pipeline

## Define functions

```{r}
slow_lm <- function(df, sleep=0) {
  Sys.sleep(sleep)
  lm(lifeExp ~ year, df)
}
```

## Set up simple plan

```{r}
drake::clean(destroy=TRUE)

gm_pipeline_simple <- drake_plan(
  data_simple = gapminder::gapminder,
  plot_simple = ggplot(data_simple, aes(x=year, y=lifeExp, group=country, color=continent)) + 
    geom_line(alpha=0.3) + theme_bw()
)
```

Run the plan:

```{r}
make(gm_pipeline_simple)
```

View output:

```{r}
readd(plot_simple)
```

## Set up more complex plan

```{r}
drake::clean(destroy=TRUE)

gm_pipeline_complex <- drake_plan(
  data = gapminder::gapminder,
  many_models = data %>%
    group_by(continent, country) %>%
    tidyr::nest() %>%
    mutate(mod = purrr::map(data, slow_lm)),
  all_countries_coefficients = many_models %>%
    mutate(tidy_mod = purrr::map(mod, broom::tidy)) %>%
    dplyr::select(-data, -mod) %>%
    tidyr::unnest() %>%
    dplyr::filter(term == 'year'),
  plot = ggplot(all_countries_coefficients, aes(continent, estimate, color = continent)) +
    geom_violin() +
    geom_point(position = position_jitter(width=0.3)) +
    theme_bw()
)

```

Run the plan:

```{r}
make(gm_pipeline_complex)
```

View output:

```{r}
readd(all_countries_coefficients)
readd(plot)
```

## Set up very complex plan

```{r}
calculate_slope <- function(df, country, sleep) {
  mod <- df %>%
    dplyr::filter(country == !!country) %>%
    slow_lm(sleep = sleep)
  
    data_frame(country=!!country, slope=coef(mod)[['year']])
}

calculate_slope(gapminder, 'New Zealand', 0)


```

Define the plan

```{r}
drake::clean(destroy=TRUE)

gm_countries <- gapminder %>% distinct(country) %>% 
  #slice(1:20) %>% 
  unlist() %>% unname() %>% as.character()

par_plan = drake_plan(
  data_par = gapminder,
  countries_par = unique(data_par$country) %>% as.character(),
  results_par = target(
    calculate_slope(df=data_par, country = country_val, sleep = 0),
    transform = map(country_val = !!gm_countries)
  ),
  results = target(
    bind_rows(results_par),
    transform = combine(results_par)
  ),
  plot_data = data_par %>%
    distinct(continent, country) %>%
    mutate_all(as.character) %>%
    inner_join(results, by='country'),
  plot = ggplot(plot_data, aes(continent, slope, color = continent)) +
    geom_violin() +
    geom_point(position = position_jitter(width=0.3)) +
    theme_bw(),
  trace=TRUE
)
```

View the plan

```{r}
par_plan
```

Make the plan
```{r}
make(par_plan)
```

View the output
```{r}
readd(plot)
```
